services:
  db_mysql:
    image: mysql:8
    container_name: db_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tasks_db
      MYSQL_USER: userdocker
      MYSQL_PASSWORD: userdocker
      MYSQL_ROOT_PASSWORD: userdocker
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_data:/var/lib/mysql
      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - app-network

  backend:
    build:
      dockerfile: docker/backend/Dockerfile
    container_name: backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db_mysql
    networks:
      - app-network

  frontend:
    build:
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    working_dir: /var/www/
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80" # phpMyAdmin sera accessible sur http://localhost:8080
    environment:
      PMA_HOST: db_mysql # le nom du service MySQL déclaré dans docker-compose (typiquement "db_mysql")
      PMA_PORT: 3306
    depends_on:
      - db_mysql
    networks:
      - app-network

volumes:
  db_data:
networks:
  app-network:
    driver: bridge
